# Generated by Django 4.2.5 on 2023-10-06 13:13

import blog.validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_managers_post_statuss_alter_post_publish_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Ismi')),
                ('surname', models.CharField(max_length=30, verbose_name='Familiya')),
                ('phone', models.CharField(max_length=13, validators=[blog.validator.validator], verbose_name='Telefon raqam')),
                ('age', models.IntegerField(unique=True)),
            ],
            options={
                'ordering': ['age'],
            },
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
