# Generated by Django 4.2.6 on 2023-10-10 15:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 10, 15, 50, 29, 430022, tzinfo=datetime.timezone.utc)),
        ),
    ]
