# Generated by Django 4.2.6 on 2023-10-12 14:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_post_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 12, 14, 23, 30, 766991, tzinfo=datetime.timezone.utc)),
        ),
    ]
